export * from "./1-Header";
export * from "./2-Profile";
export * from "./3-About";
export * from "./4-Skill";
export * from "./5-Experienses";
export * from "./6-Work";
export * from "./7-GetInTouch";
export * from "./8-Footer";
export * from "./head";